import pytest
from spectools.utils import *
import astropy.io.fits as pf
from numpy.testing import assert_almost_equal

def header(filename):
    return pf.getheader(filename)

def test_wavelength():
    """Wavelength generated by specutils.Spectrum1D"""
    filename = 'data/hermes_spec.fits'
    wavelength_from_function = wavelength(header(filename))
    assert_almost_equal(wavelength_from_function[0],get_keyword(header(filename), 'CRVAL1'))
